version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_VAULT: file
      KC_VAULT_DIR: /opt/keycloak/vault
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/vault:/opt/keycloak/vault:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
      - ldap

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - bionicpro-auth

  ldap:
    build:
      context: ./ldap
      dockerfile: Dockerfile
    environment:
      LDAP_ORGANISATION: BionicPRO Foreign Office
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      LISTEN_ADDR: ":8000"
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      KEYCLOAK_PUBLIC_URL: http://localhost:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: reports-frontend
      BACKEND_PUBLIC_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:3000
      REPORTS_API_URL: ""
      COOKIE_NAME: bionicpro_session
      COOKIE_SECURE: "false"
      SESSION_TTL_SECONDS: "900"
    depends_on:
      - keycloak
